platform :ios, '12.0'

target 'LogWebSDK_Example' do
  use_frameworks!
  
  # 本地开发使用
  pod 'LogWebSDK', :path => '../', :configurations => ['Debug']
  
  # 或者使用发布版本
  # pod 'LogWebSDK'
  
  pod 'CocoaLumberjack'
  
end
