platform :ios, '12.0'

target 'LogWebSDK_Example' do
  use_frameworks!

  pod 'LogWebSDK', :path => '../', :configurations => ['Debug']

  pod 'CocoaLumberjack'

end

target 'LogWebSDKTests' do
  use_frameworks!
  inherit! :search_paths

  pod 'LogWebSDK/Core', :path => '../'
  pod 'CocoaLumberjack'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
